var a = 1;
var b = 2;
var c = 3;
var d = 4;
var e = 5;
var f = 6;
var g = 7;
var h = 8;
var i = 9;
var j = 10;
console.log(a + j);
console.log(b + e);
console.log(c - a);
console.log(f - i);
console.log(d * j);
console.log(e * e);
console.log(i / c);
console.log(h / b);
console.log(a++);
console.log(b++);
console.log(c--);
console.log(d--);
